In [2]:
import pandas as pd
import numpy as np
from itertools import combinations, product
from ast import literal_eval

In [3]:
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed

In [4]:
atp_2016 = pd.read_csv("atp_2016.csv")
atp_2017_pre_wim = pd.read_csv("atp_2017_pre_wim.csv")

In [4]:
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed
##atp_2015 is now 2016 and 2017 pre wimbledon but the variable name has not changed

In [5]:
atp_2015 = pd.concat([atp_2016, atp_2017_pre_wim])

In [6]:
frames = [atp_2015["winner_name"],atp_2015["loser_name"]]

In [7]:
results = pd.concat(frames)

In [8]:
players = results.unique()

In [9]:
atp_2015_win_lose = atp_2015[['winner_name','loser_name']]

In [10]:
atp_2015_win_lose = atp_2015_win_lose.dropna(axis=0,how="any")

In [11]:
atp_2015_opponents_win = atp_2015_win_lose.groupby("winner_name")["loser_name"].apply(list)
atp_2015_opponents_loss = atp_2015_win_lose.groupby("loser_name")["winner_name"].apply(list)
atp_2015_opponents_loss = pd.DataFrame(atp_2015_opponents_loss)
atp_2015_opponents_loss = atp_2015_opponents_loss.reset_index()
atp_2015_opponents_win = pd.DataFrame(atp_2015_opponents_win)
atp_2015_opponents_win = atp_2015_opponents_win.reset_index()
atp_2015_opponents_win = atp_2015_opponents_win.rename(index=str, columns={"winner_name": "name","loser_name":"wins"})
atp_2015_opponents_loss = atp_2015_opponents_loss.rename(index=str, columns={"loser_name": "name","winner_name":"losses"})

In [12]:
merge_table = pd.merge(atp_2015_opponents_loss, atp_2015_opponents_win, on="name", how="outer")
merge_table.to_csv("merge_table_3.csv")

In [28]:
##i manually changed the csv..dont judge :P
##the players with no wins need to win ["bye"]

In [14]:
merge_table = pd.read_csv("merge_table_3.csv")
del merge_table["Unnamed: 0"]
merge_table.head()

,name,losses,wins
0,Abdullah Maqdas,"['Jirat Navasirisomboon', 'Wishaya Trongcharoe...",['Bye']
1,Adam Hornby,['Christopher Diaz Figueroa'],['Bye']
2,Adam Pavlasek,"['Jeremy Chardy', 'Nikoloz Basilashvili', 'Rya...","['Roberto Carballes Baena', 'Marcel Granollers..."
3,Aditya Hari Sasongko,['Ruben Gonzales'],['Bye']
4,Adrian Mannarino,"['Nicolas Mahut', 'Samuel Groth', 'Roberto Bau...","['Marius Copil', 'Evgeny Donskoy', 'Tatsuma It..."

In [15]:
##fun fact: the lists are strings and not lists! this changes it back (necessary for later stuff)
merge_table.loc[:,'losses'] = merge_table.loc[:,'losses'].apply(lambda x: literal_eval(x))
merge_table.loc[:,'wins'] = merge_table.loc[:,'wins'].apply(lambda x: literal_eval(x))

In [16]:
merge_table.head()

,name,losses,wins
0,Abdullah Maqdas,"[Jirat Navasirisomboon, Wishaya Trongcharoench...",[Bye]
1,Adam Hornby,[Christopher Diaz Figueroa],[Bye]
2,Adam Pavlasek,"[Jeremy Chardy, Nikoloz Basilashvili, Ryan Har...","[Roberto Carballes Baena, Marcel Granollers, M..."
3,Aditya Hari Sasongko,[Ruben Gonzales],[Bye]
4,Adrian Mannarino,"[Nicolas Mahut, Samuel Groth, Roberto Bautista...","[Marius Copil, Evgeny Donskoy, Tatsuma Ito, Ma..."

In [17]:
prod = list(product(atp_2015_win_lose['loser_name'].unique(), atp_2015_win_lose['loser_name'].unique()))

In [18]:
len(prod)

189225

In [19]:
all_possible_matches = pd.DataFrame(prod)

In [20]:
all_possible_matches.head()

               0                1
0  Roger Federer    Roger Federer
1  Roger Federer    Dominic Thiem
2  Roger Federer    Bernard Tomic
3  Roger Federer  Grigor Dimitrov
4  Roger Federer      Marin Cilic

In [21]:
all_possible_matches = all_possible_matches.rename(index=str, columns={0: "player_1",1:"player_2"})

In [22]:
all_possible_matches = all_possible_matches.drop(all_possible_matches[all_possible_matches.player_1 == all_possible_matches.player_2].index)

In [24]:
all_possible_matches.head()

        player_1         player_2
1  Roger Federer    Dominic Thiem
2  Roger Federer    Bernard Tomic
3  Roger Federer  Grigor Dimitrov
4  Roger Federer      Marin Cilic
5  Roger Federer    Lucas Pouille

In [25]:
# all_possible_matches["player_1_wins"] = merge_table.loc([merge_table['name'] == all_possible_matches["player_1"], ['wins']])

In [26]:
merge_table_test = merge_table.rename(index=str, columns = {"name":"player_1"})

In [27]:
merge_table_test.head()

,player_1,losses,wins
0,Abdullah Maqdas,"[Jirat Navasirisomboon, Wishaya Trongcharoench...",[Bye]
1,Adam Hornby,[Christopher Diaz Figueroa],[Bye]
2,Adam Pavlasek,"[Jeremy Chardy, Nikoloz Basilashvili, Ryan Har...","[Roberto Carballes Baena, Marcel Granollers, M..."
3,Aditya Hari Sasongko,[Ruben Gonzales],[Bye]
4,Adrian Mannarino,"[Nicolas Mahut, Samuel Groth, Roberto Bautista...","[Marius Copil, Evgeny Donskoy, Tatsuma Ito, Ma..."

In [28]:
matching_merge = pd.merge(all_possible_matches,merge_table_test, on = "player_1", how = "outer")

In [29]:
matching_merge.head()

,player_1,player_2,losses,wins
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."

In [30]:
matching_merge = matching_merge.rename(index = str, columns = {"losses": "player_1_losses","wins": "player_1_wins"})

In [31]:
matching_merge.head()

,player_1,player_2,player_1_losses,player_1_wins
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,..."

In [32]:
merge_table_test = merge_table.rename(index=str, columns = {"name":"player_2"})

In [33]:
merge_table_test.head()

,player_2,losses,wins
0,Abdullah Maqdas,"[Jirat Navasirisomboon, Wishaya Trongcharoench...",[Bye]
1,Adam Hornby,[Christopher Diaz Figueroa],[Bye]
2,Adam Pavlasek,"[Jeremy Chardy, Nikoloz Basilashvili, Ryan Har...","[Roberto Carballes Baena, Marcel Granollers, M..."
3,Aditya Hari Sasongko,[Ruben Gonzales],[Bye]
4,Adrian Mannarino,"[Nicolas Mahut, Samuel Groth, Roberto Bautista...","[Marius Copil, Evgeny Donskoy, Tatsuma Ito, Ma..."

In [34]:
matching_merge_1 = pd.merge(all_possible_matches,merge_table_test, on = "player_2", how = "outer")

In [35]:
matching_merge_1 = matching_merge_1.rename(index = str, columns = {"losses": "player_2_losses","wins": "player_2_wins"})

In [36]:
matching_merge_1.head()

,player_1,player_2,player_2_losses,player_2_wins
0,Roger Federer,Dominic Thiem,"[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."
1,Bernard Tomic,Dominic Thiem,"[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."
2,Grigor Dimitrov,Dominic Thiem,"[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."
3,Marin Cilic,Dominic Thiem,"[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."
4,Lucas Pouille,Dominic Thiem,"[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."

In [37]:
attempt_merge = pd.merge(matching_merge, matching_merge_1,  how='left', left_on=['player_1','player_2'], right_on = ['player_1','player_2'])

In [38]:
##i dont know why there are NAs

attempt_merge1 = attempt_merge.dropna(axis=0,how="any")

In [39]:
# del attempt_merge1["player_1_losses_in_player_2_wins"]
# del attempt_merge1["player_2_losses_in_player_1_wins"]
# del attempt_merge1["player_1_wins_in_player_2_wins"]
# del attempt_merge1["player_1_losses_in_player_2_losses"]

In [40]:
attempt_merge1.head()

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le..."
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Teymuraz Gabashvili, Andy Murra...","[Kei Nishikori, Radek Stepanek, Nicolas Mahut,..."
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Viktor Troicki, Roger Federer,...","[Viktor Troicki, Gilles Simon, Gilles Muller, ..."
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Dominic Thiem, Roberto Bautista Agut, Alexand...","[Hyeon Chung, Thiemo De Bakker, Albert Ramos, ..."
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Milos Raonic, Andrey Kuznetsov,...","[David Goffin, Yoshihito Nishioka, David Ferre..."

In [41]:
attempt_merge1['player_1_losses_in_player_2_wins'] = [(list(set(a).intersection(set(b)))) for a, b in zip(attempt_merge1.player_1_losses,attempt_merge1.player_2_wins)]
attempt_merge1['player_2_losses_in_player_1_wins'] = [list(set(a).intersection(set(b))) for a, b in zip(attempt_merge1.player_2_losses,attempt_merge1.player_1_wins)]
attempt_merge1['player_1_wins_in_player_2_wins'] = [list(set(a).intersection(set(b))) for a, b in zip(attempt_merge1.player_1_wins,attempt_merge1.player_2_wins)]
attempt_merge1['player_1_losses_in_player_2_losses'] = [list(set(a).intersection(set(b))) for a, b in zip(attempt_merge1.player_1_losses,attempt_merge1.player_2_losses)]

In [42]:
attempt_merge1.head()

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le...","[Alexander Zverev, Novak Djokovic]","[Jack Sock, Guido Pella, Grigor Dimitrov, Kei ...","[Jack Sock, Grigor Dimitrov, Marin Cilic, Beno...","[Milos Raonic, Novak Djokovic, Jo Wilfried Tso..."
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Teymuraz Gabashvili, Andy Murra...","[Kei Nishikori, Radek Stepanek, Nicolas Mahut,...",[Tommy Haas],"[Benoit Paire, Tomas Berdych, Daniel Evans, Ro...","[Kei Nishikori, Mischa Zverev, Roberto Bautist...","[Milos Raonic, Dominic Thiem]"
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Viktor Troicki, Roger Federer,...","[Viktor Troicki, Gilles Simon, Gilles Muller, ...","[Milos Raonic, Dominic Thiem]","[Jack Sock, Guido Pella, Kei Nishikori, Daniel...","[Kei Nishikori, David Goffin, Milos Raonic, St...","[Alexander Zverev, Dominic Thiem, Novak Djokovic]"
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Dominic Thiem, Roberto Bautista Agut, Alexand...","[Hyeon Chung, Thiemo De Bakker, Albert Ramos, ...","[Milos Raonic, Novak Djokovic]","[Jack Sock, Nick Kyrgios, Taylor Harry Fritz, ...","[Grigor Dimitrov, Benoit Paire, Kei Nishikori,...","[Alexander Zverev, Dominic Thiem, Jo Wilfried ..."
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Milos Raonic, Andrey Kuznetsov,...","[David Goffin, Yoshihito Nishioka, David Ferre...","[Evgeny Donskoy, Dominic Thiem]","[Nick Kyrgios, Grigor Dimitrov, Kei Nishikori,...","[Benoit Paire, Jan Lennard Struff, Roberto Bau...","[Milos Raonic, Jo Wilfried Tsonga]"

In [43]:
#[list(len(a+b)) for a, b in zip(attempt_merge1.player_1_losses_in_player_2_wins,attempt_merge1.player_2_losses_in_player_1_wins)]

In [44]:
##for the numbers
attempt_merge1['player_1_losses_in_player_2_wins'] = [len((list(set(a).intersection(set(b))))) for a, b in zip(attempt_merge1.player_1_losses,attempt_merge1.player_2_wins)]
attempt_merge1['player_2_losses_in_player_1_wins'] = [len(list(set(a).intersection(set(b)))) for a, b in zip(attempt_merge1.player_2_losses,attempt_merge1.player_1_wins)]
attempt_merge1['player_1_wins_in_player_2_wins'] = [len(list(set(a).intersection(set(b)))) for a, b in zip(attempt_merge1.player_1_wins,attempt_merge1.player_2_wins)]
attempt_merge1['player_1_losses_in_player_2_losses'] = [len(list(set(a).intersection(set(b)))) for a, b in zip(attempt_merge1.player_1_losses,attempt_merge1.player_2_losses)]

In [45]:
attempt_merge1.head()

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le...",2,15,16,4
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Teymuraz Gabashvili, Andy Murra...","[Kei Nishikori, Radek Stepanek, Nicolas Mahut,...",1,9,6,2
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Viktor Troicki, Roger Federer,...","[Viktor Troicki, Gilles Simon, Gilles Muller, ...",2,12,13,3
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Dominic Thiem, Roberto Bautista Agut, Alexand...","[Hyeon Chung, Thiemo De Bakker, Albert Ramos, ...",2,10,12,3
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Milos Raonic, Andrey Kuznetsov,...","[David Goffin, Yoshihito Nishioka, David Ferre...",2,6,10,2

In [46]:
attempt_merge1["parameters_value"] = [(a/(a+b))*(1/10) for a, b in zip(attempt_merge1.player_1_losses_in_player_2_wins,attempt_merge1.player_2_losses_in_player_1_wins)]

C:\Users\gizmo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in longlong_scalars
  """Entry point for launching an IPython kernel.

In [47]:
attempt_merge1.head()

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses,parameters_value
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le...",2,15,16,4,0.011765
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Teymuraz Gabashvili, Andy Murra...","[Kei Nishikori, Radek Stepanek, Nicolas Mahut,...",1,9,6,2,0.010000
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Viktor Troicki, Roger Federer,...","[Viktor Troicki, Gilles Simon, Gilles Muller, ...",2,12,13,3,0.014286
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Dominic Thiem, Roberto Bautista Agut, Alexand...","[Hyeon Chung, Thiemo De Bakker, Albert Ramos, ...",2,10,12,3,0.016667
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Milos Raonic, Andrey Kuznetsov,...","[David Goffin, Yoshihito Nishioka, David Ferre...",2,6,10,2,0.025000

In [48]:
final_merge_thing_help = attempt_merge1.fillna(0)

In [49]:
final_merge_thing_help.to_csv("matchups_parameters_3.csv")

In [50]:
final_merge_thing_help.head()

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses,parameters_value
0,Roger Federer,Dominic Thiem,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Gilles Muller, David Goffin, G...","[Marin Cilic, Denis Kudla, James Duckworth, Le...",2,15,16,4,0.011765
1,Roger Federer,Bernard Tomic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Teymuraz Gabashvili, Andy Murra...","[Kei Nishikori, Radek Stepanek, Nicolas Mahut,...",1,9,6,2,0.010000
2,Roger Federer,Grigor Dimitrov,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Roger Federer, Viktor Troicki, Roger Federer,...","[Viktor Troicki, Gilles Simon, Gilles Muller, ...",2,12,13,3,0.014286
3,Roger Federer,Marin Cilic,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Dominic Thiem, Roberto Bautista Agut, Alexand...","[Hyeon Chung, Thiemo De Bakker, Albert Ramos, ...",2,10,12,3,0.016667
4,Roger Federer,Lucas Pouille,"[Milos Raonic, Novak Djokovic, Jo Wilfried Tso...","[Dominic Thiem, Grigor Dimitrov, Tobias Kamke,...","[Milos Raonic, Milos Raonic, Andrey Kuznetsov,...","[David Goffin, Yoshihito Nishioka, David Ferre...",2,6,10,2,0.025000