In [3]:
import pandas as pd
import numpy as np

In [4]:
##ATP 2015 is now atp_2016 but the variable name has not changed
##ATP 2015 is now atp_2016 but the variable name has not changed
##ATP 2015 is now atp_2016 but the variable name has not changed

In [5]:
atp_2015 = pd.read_csv("atp_2016.csv")
atp_2015.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2016-M020,Brisbane,Hard,32.0,A,20160104.0,300.0,105683.0,4.0,NaN,...,1.0,7.0,3.0,61.0,34.0,25.0,14.0,10.0,3.0,5.0
1,2016-M020,Brisbane,Hard,32.0,A,20160104.0,299.0,103819.0,1.0,NaN,...,1.0,2.0,4.0,55.0,31.0,18.0,9.0,8.0,2.0,6.0
2,2016-M020,Brisbane,Hard,32.0,A,20160104.0,298.0,105683.0,4.0,NaN,...,4.0,10.0,3.0,84.0,54.0,41.0,16.0,12.0,2.0,2.0
3,2016-M020,Brisbane,Hard,32.0,A,20160104.0,297.0,103819.0,1.0,NaN,...,1.0,8.0,2.0,104.0,62.0,46.0,21.0,16.0,8.0,11.0
4,2016-M020,Brisbane,Hard,32.0,A,20160104.0,296.0,106233.0,8.0,NaN,...,2.0,11.0,2.0,98.0,52.0,41.0,27.0,15.0,7.0,8.0

In [6]:
atp_2015.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'winner_rank', 'winner_rank_points', 'loser_id', 'loser_seed',
       'loser_entry', 'loser_name', 'loser_hand', 'loser_ht', 'loser_ioc',
       'loser_age', 'loser_rank', 'loser_rank_points', 'score', 'best_of',
       'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon',
       'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df',
       'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved',
       'l_bpFaced'],
      dtype='object')

In [7]:
surface_grass = atp_2015['surface'] == "Grass"
surface_clay = atp_2015["surface"]=="Clay"
surface_hard = atp_2015["surface"]=="Hard"
surface_clay_df = atp_2015[surface_clay]
surface_hard_df = atp_2015[surface_hard]
surface_df = atp_2015[surface_grass]

In [8]:
player_win_right = atp_2015["winner_hand"] == "R"
player_winners_right_df = atp_2015[player_win_right]
player_loser_right = atp_2015["loser_hand"] =="R"
player_loser_right_df = atp_2015[player_loser_right]
player_win_left = atp_2015["winner_hand"] == "L"
player_winner_left_df = atp_2015[player_win_left]
player_loser_left = atp_2015["loser_hand"] =="L"
player_loser_left_df = atp_2015[player_loser_left]

In [9]:
winners_right = pd.DataFrame(player_loser_right_df["winner_name"].value_counts())
losers_right = pd.DataFrame(player_winners_right_df["loser_name"].value_counts())

In [10]:
winners_left = pd.DataFrame(player_loser_left_df["winner_name"].value_counts())
losers_left = pd.DataFrame(player_winner_left_df["loser_name"].value_counts())

In [11]:
combined_RL1 = winners_left.join(losers_left, how = "outer")
combined_RL_Left = combined_RL1.fillna(0)
combined_RL_Left = combined_RL_Left.rename(index = str, columns = {"winner_name": "wins", "loser_name": "losses"})
combined_RL_Left["Left_hand_win_pct"] = combined_RL_Left["wins"]/(combined_RL_Left["wins"]+combined_RL_Left["losses"])
combined_RL_Left.head()

                  wins  losses  Left_hand_win_pct
Adrian Mannarino   4.0     4.0           0.500000
Adrian Ungur       0.0     1.0           0.000000
Agustin Velotti    0.0     1.0           0.000000
Albert Montanes    1.0     5.0           0.166667
Albert Ramos       7.0     3.0           0.700000

In [12]:
combined_RL = winners_right.join(losers_right,how = "outer")
combined_RL_Right = combined_RL.fillna(0)
combined_RL_Right= combined_RL_Right.rename(index = str, columns = {"winner_name": "wins", "loser_name": "losses"})
combined_RL_Right["right_hand_win_pct"] = combined_RL_Right["wins"]/(combined_RL_Right["wins"]+combined_RL_Right["losses"])
combined_RL_Right.head()

                  wins  losses  right_hand_win_pct
Adam Pavlasek      3.0     3.0            0.500000
Adrian Mannarino  21.0    24.0            0.466667
Adrian Ungur       1.0     2.0            0.333333
Akira Santillan    0.0     2.0            0.000000
Albano Olivetti    0.0     1.0            0.000000

In [13]:
# combined_RL_Right.head()

In [14]:
del combined_RL_Right["wins"]
del combined_RL_Left["wins"]
del combined_RL_Right["losses"]
del combined_RL_Left["losses"]

In [15]:
surface_df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
1348,2016-M010,s-Hertogenbosch,Grass,32.0,A,20160606.0,300.0,103917.0,8.0,NaN,...,4.0,9.0,1.0,62.0,38.0,25.0,10.0,10.0,0.0,3.0
1349,2016-M010,s-Hertogenbosch,Grass,32.0,A,20160606.0,299.0,104180.0,7.0,NaN,...,0.0,21.0,6.0,72.0,47.0,42.0,15.0,12.0,0.0,0.0
1350,2016-M010,s-Hertogenbosch,Grass,32.0,A,20160606.0,298.0,103917.0,8.0,NaN,...,2.0,19.0,1.0,98.0,64.0,50.0,20.0,16.0,6.0,8.0
1351,2016-M010,s-Hertogenbosch,Grass,32.0,A,20160606.0,297.0,104180.0,7.0,NaN,...,5.0,3.0,3.0,102.0,63.0,45.0,29.0,16.0,4.0,5.0
1352,2016-M010,s-Hertogenbosch,Grass,32.0,A,20160606.0,296.0,103333.0,3.0,NaN,...,3.0,4.0,5.0,54.0,30.0,24.0,10.0,9.0,4.0,6.0

In [16]:
winners_clay = pd.DataFrame(surface_clay_df["winner_name"].value_counts())
losers_clay = pd.DataFrame(surface_clay_df["loser_name"].value_counts())
winners_hard = pd.DataFrame(surface_hard_df["winner_name"].value_counts())
losers_hard = pd.DataFrame(surface_hard_df["loser_name"].value_counts())
winners_grass = pd.DataFrame(surface_df["winner_name"].value_counts())
losers_grass = pd.DataFrame(surface_df["loser_name"].value_counts())

In [17]:
winners_clay = winners_clay.reset_index()
losers_clay = losers_clay.reset_index()
winners_hard = winners_hard.reset_index()
losers_hard = losers_hard.reset_index()
winner_grass = winners_grass.reset_index()
losers_grass = losers_grass.reset_index()

In [18]:
merged_win_lose_clay = pd.merge(winners_clay, losers_clay, how ="outer")
merged_win_lose_hard = pd.merge(winners_hard, losers_hard, how = "outer")
merged_win_lose_grass = pd.merge(winner_grass, losers_grass, how = "outer")

In [19]:
merged_win_lose_clay = merged_win_lose_clay.rename(index = str, columns = {"winner_name": "wins", "loser_name": "losses"})
merged_win_lose_hard = merged_win_lose_hard.rename(index = str, columns = {"winner_name": "wins", "loser_name": "losses"})
merged_win_lose_grass = merged_win_lose_grass.rename(index=str, columns={"winner_name": "wins","loser_name":"losses"})

In [20]:
merged_win_lose_clay = merged_win_lose_clay.fillna(0)
merged_win_lose_hard  = merged_win_lose_hard.fillna(0)
merged_win_lose_grass = merged_win_lose_grass.fillna(0)

In [21]:
merged_win_lose_grass["win_pct_grass"] = merged_win_lose_grass["wins"]/(merged_win_lose_grass["wins"]+merged_win_lose_grass["losses"])
merged_win_lose_clay["win_pct_clay"] = merged_win_lose_clay["wins"]/(merged_win_lose_clay["wins"]+merged_win_lose_clay["losses"])
merged_win_lose_hard["win_pct_hard"] = merged_win_lose_hard["wins"]/(merged_win_lose_hard["wins"]+merged_win_lose_hard["losses"])

In [22]:
merged_win_lose_grass = merged_win_lose_grass.set_index("index")
merged_win_lose_hard = merged_win_lose_hard.set_index("index")
merged_win_lose_clay = merged_win_lose_clay.set_index("index")

In [23]:
del merged_win_lose_grass["wins"]
del merged_win_lose_grass["losses"]
del merged_win_lose_clay["wins"]
del merged_win_lose_clay["losses"]
del merged_win_lose_hard["wins"]
del merged_win_lose_hard["losses"]

In [24]:
merged_win_lose_hard.head()

                       win_pct_hard
index
Novak Djokovic             0.882353
Andy Murray                0.900000
Kei Nishikori              0.727273
Gael Monfils               0.740000
Roberto Bautista Agut      0.686275

In [25]:
players = atp_2015["winner_name"]

In [26]:
players_list = players.unique()

In [28]:
##change players_list to players_list_test for testing
stat_player_df = pd.DataFrame({'name':players_list})

In [29]:
len(stat_player_df)

209

In [30]:
grouped_atp_2015 = atp_2015.groupby(["winner_name"])

In [31]:
aces = grouped_atp_2015["w_ace"].sum()
service_games = grouped_atp_2015["w_SvGms"].sum()
first_serve_in = grouped_atp_2015["w_1stIn"].sum()
first_serves_won = grouped_atp_2015["w_1stWon"].sum()
doubfts = grouped_atp_2015["w_df"].sum()
total_brk_saved = grouped_atp_2015["w_bpSaved"].sum()
total_brk_faced = grouped_atp_2015["w_bpFaced"].sum()
rt_games_total = grouped_atp_2015["l_SvGms"].sum()
break_point_opp_total = grouped_atp_2015["l_bpFaced"].sum()
break_point_opp_loss = grouped_atp_2015["l_bpSaved"].sum()
svpt_total = grouped_atp_2015["w_svpt"].sum()

In [32]:
grouped_atp_2015_losers = atp_2015.groupby(["loser_name"])

In [33]:
aces_1 = grouped_atp_2015_losers["l_ace"].sum()
service_games_1 = grouped_atp_2015_losers["l_SvGms"].sum()
first_serve_in_l = grouped_atp_2015_losers["l_1stIn"].sum()
first_serves_won_l = grouped_atp_2015_losers["l_1stWon"].sum()
doubfts_l = grouped_atp_2015_losers["l_df"].sum()
total_brk_saved_l = grouped_atp_2015_losers["l_bpSaved"].sum()
total_brk_faced_l = grouped_atp_2015_losers["l_bpFaced"].sum()
rt_games_total_l = grouped_atp_2015_losers["w_SvGms"].sum()
break_point_opp_total_l = grouped_atp_2015_losers["w_bpFaced"].sum()
break_point_opp_loss_l = grouped_atp_2015_losers["w_bpSaved"].sum()
svpt_total_l = grouped_atp_2015_losers["l_svpt"].sum()

In [34]:
updated_stats_players_l = pd.DataFrame({"aces":aces_1,
                                   "service_games":service_games_1,
                                     "first_serve_in": first_serve_in_l,
                                     "first_serves_won": first_serves_won_l,
                                     "doubfts": doubfts_l,
                                     "total_brk_saved": total_brk_saved_l,
                                     "total_brk_faced": total_brk_faced_l,
                                     "rt_games_total": rt_games_total_l,
                                     "break_point_opp_total": break_point_opp_total_l,
                                     "break_point_opp_loss": break_point_opp_loss_l,
                                     "svpt_total": svpt_total_l})
updated_stats_players_l.head(20)

,aces,break_point_opp_loss,break_point_opp_total,doubfts,first_serve_in,first_serves_won,rt_games_total,service_games,svpt_total,total_brk_faced,total_brk_saved
loser_name,,,,,,,,,,,
Adam Pavlasek,20.0,5.0,8.0,12.0,163.0,116.0,41.0,41.0,266.0,23.0,13.0
Adrian Mannarino,114.0,93.0,141.0,97.0,1256.0,834.0,330.0,323.0,2087.0,243.0,133.0
Adrian Ungur,4.0,10.0,17.0,13.0,177.0,103.0,41.0,40.0,277.0,38.0,23.0
Agustin Velotti,1.0,9.0,10.0,3.0,35.0,22.0,9.0,9.0,63.0,9.0,5.0
Akira Santillan,6.0,6.0,6.0,4.0,61.0,39.0,18.0,18.0,112.0,12.0,6.0
Albano Olivetti,56.0,1.0,1.0,17.0,128.0,108.0,36.0,35.0,218.0,13.0,11.0
Albert Montanes,29.0,13.0,21.0,26.0,399.0,266.0,105.0,102.0,646.0,59.0,32.0
Albert Ramos,101.0,100.0,156.0,92.0,1491.0,970.0,376.0,367.0,2435.0,263.0,145.0
Aldin Setkic,6.0,1.0,2.0,8.0,93.0,58.0,16.0,15.0,133.0,14.0,10.0
Alejandro Falla,4.0,1.0,2.0,0.0,32.0,20.0,9.0,8.0,49.0,6.0,2.0
Alejandro Gonzalez,11.0,8.0,16.0,8.0,166.0,100.0,42.0,42.0,286.0,31.0,18.0
Alessandro Giannessi,5.0,10.0,11.0,7.0,70.0,42.0,16.0,15.0,107.0,12.0,8.0
Alex Kuznetsov,12.0,4.0,7.0,2.0,92.0,63.0,25.0,25.0,168.0,11.0,5.0
Alexander Bublik,9.0,7.0,13.0,9.0,83.0,60.0,23.0,23.0,145.0,18.0,9.0
Alexander Kudryavtsev,9.0,3.0,6.0,7.0,101.0,75.0,29.0,27.0,177.0,15.0,8.0
Alexander Lazov,1.0,1.0,2.0,2.0,36.0,20.0,7.0,8.0,54.0,11.0,5.0
Alexander Sarkissian,9.0,3.0,5.0,5.0,78.0,44.0,17.0,17.0,130.0,20.0,11.0
Alexander Ward,10.0,4.0,5.0,8.0,125.0,85.0,29.0,28.0,204.0,27.0,18.0
Alexander Zverev,129.0,102.0,148.0,127.0,1188.0,802.0,308.0,301.0,1988.0,204.0,106.0
Alexandr Dolgopolov,98.0,51.0,74.0,69.0,707.0,486.0,194.0,191.0,1287.0,147.0,86.0

In [35]:
updated_stats_players = pd.DataFrame({"aces":aces,
                                   "service_games":service_games,
                                     "first_serve_in": first_serve_in,
                                     "first_serves_won": first_serves_won,
                                     "doubfts": doubfts,
                                     "total_brk_saved": total_brk_saved,
                                     "total_brk_faced": total_brk_faced,
                                     "rt_games_total": rt_games_total,
                                     "break_point_opp_total": break_point_opp_total,
                                     "break_point_opp_loss": break_point_opp_loss,
                                     "svpt_total": svpt_total})
updated_stats_players.head()

,aces,break_point_opp_loss,break_point_opp_total,doubfts,first_serve_in,first_serves_won,rt_games_total,service_games,svpt_total,total_brk_faced,total_brk_saved
winner_name,,,,,,,,,,,
Adam Pavlasek,16.0,14.0,28.0,8.0,164.0,115.0,38.0,40.0,276.0,26.0,19.0
Adrian Mannarino,150.0,134.0,242.0,72.0,1226.0,913.0,321.0,326.0,2070.0,145.0,96.0
Adrian Ungur,0.0,2.0,8.0,0.0,25.0,18.0,9.0,9.0,59.0,7.0,4.0
Albert Montanes,20.0,34.0,59.0,19.0,225.0,184.0,70.0,69.0,388.0,12.0,6.0
Albert Ramos,138.0,187.0,331.0,85.0,1866.0,1322.0,441.0,451.0,2897.0,235.0,164.0

In [36]:
frames = [updated_stats_players,updated_stats_players_l]

In [37]:
results = pd.concat(frames)

In [38]:
results = results.reset_index()

In [39]:
full_player_stats = results.groupby(["index"])

In [40]:
len(full_player_stats.groups)

303

In [41]:
total_player_stats = full_player_stats.sum()

In [42]:
total_player_stats["ace_pct"] = total_player_stats["aces"]/total_player_stats["svpt_total"]
total_player_stats["df_pct"] = total_player_stats["doubfts"]/total_player_stats["svpt_total"]
total_player_stats["first_serve_won_pct"] = total_player_stats["first_serves_won"]/total_player_stats["first_serve_in"]
total_player_stats["broken_pct"] = (total_player_stats["total_brk_faced"]-total_player_stats["total_brk_saved"])/total_player_stats["service_games"]
total_player_stats["breaking_pct"] = (total_player_stats["break_point_opp_total"]-total_player_stats["break_point_opp_loss"])/total_player_stats["rt_games_total"]
total_player_stats["break_conversion_pct"] = (total_player_stats["break_point_opp_total"]-total_player_stats["break_point_opp_loss"])/total_player_stats["break_point_opp_total"]

In [43]:
total_player_stats = total_player_stats.fillna(0)
total_player_stats.head()

,aces,break_point_opp_loss,break_point_opp_total,doubfts,first_serve_in,first_serves_won,rt_games_total,service_games,svpt_total,total_brk_faced,total_brk_saved,ace_pct,df_pct,first_serve_won_pct,broken_pct,breaking_pct,break_conversion_pct
index,,,,,,,,,,,,,,,,,
Adam Pavlasek,36.0,19.0,36.0,20.0,327.0,231.0,79.0,81.0,542.0,49.0,32.0,0.066421,0.036900,0.706422,0.209877,0.215190,0.472222
Adrian Mannarino,264.0,227.0,383.0,169.0,2482.0,1747.0,651.0,649.0,4157.0,388.0,229.0,0.063507,0.040654,0.703868,0.244992,0.239631,0.407311
Adrian Ungur,4.0,12.0,25.0,13.0,202.0,121.0,50.0,49.0,336.0,45.0,27.0,0.011905,0.038690,0.599010,0.367347,0.260000,0.520000
Agustin Velotti,1.0,9.0,10.0,3.0,35.0,22.0,9.0,9.0,63.0,9.0,5.0,0.015873,0.047619,0.628571,0.444444,0.111111,0.100000
Akira Santillan,6.0,6.0,6.0,4.0,61.0,39.0,18.0,18.0,112.0,12.0,6.0,0.053571,0.035714,0.639344,0.333333,0.000000,0.000000

In [44]:
total_player_stats = total_player_stats.join(merged_win_lose_grass,how = "outer")

In [45]:
total_player_stats = total_player_stats.join(merged_win_lose_clay, how = "outer")
total_player_stats = total_player_stats.join(merged_win_lose_hard, how = "outer")
total_player_stats = total_player_stats.join(combined_RL_Left, how = "outer")
total_player_stats = total_player_stats.join(combined_RL_Right, how = "outer")

In [50]:
total_player_stats = total_player_stats.fillna(0)

In [51]:
total_player_stats.head()

,aces,break_point_opp_loss,break_point_opp_total,doubfts,first_serve_in,first_serves_won,rt_games_total,service_games,svpt_total,total_brk_faced,...,df_pct,first_serve_won_pct,broken_pct,breaking_pct,break_conversion_pct,win_pct_grass,win_pct_clay,win_pct_hard,Left_hand_win_pct,right_hand_win_pct
Adam Pavlasek,36.0,19.0,36.0,20.0,327.0,231.0,79.0,81.0,542.0,49.0,...,0.036900,0.706422,0.209877,0.215190,0.472222,0.000000,0.600000,0.0000,0.0,0.500000
Adrian Mannarino,264.0,227.0,383.0,169.0,2482.0,1747.0,651.0,649.0,4157.0,388.0,...,0.040654,0.703868,0.244992,0.239631,0.407311,0.615385,0.444444,0.4375,0.5,0.466667
Adrian Ungur,4.0,12.0,25.0,13.0,202.0,121.0,50.0,49.0,336.0,45.0,...,0.038690,0.599010,0.367347,0.260000,0.520000,0.000000,0.250000,0.0000,0.0,0.333333
Agustin Velotti,1.0,9.0,10.0,3.0,35.0,22.0,9.0,9.0,63.0,9.0,...,0.047619,0.628571,0.444444,0.111111,0.100000,0.000000,0.000000,0.0000,0.0,0.000000
Akira Santillan,6.0,6.0,6.0,4.0,61.0,39.0,18.0,18.0,112.0,12.0,...,0.035714,0.639344,0.333333,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000

In [46]:
##matchups_2016 is now matchups_2017 but the variable name is not has not changed
##matchups_2016 is now matchups_2017 but the variable name is not has not changed
##matchups_2016 is now matchups_2017 but the variable name is not has not changed

In [56]:
matchups_2016 = pd.read_csv("2017_match_results.csv")
# matchups_2016 = matchups_2016[['Player 1.1', 'Player 2.1', 'Player_1_Win.1']]
matchups_2016.head()

,surface,player_1_win,player_1,Player_1_hand,Player_1_age,player_2,Player_2_hand,Player_2_age
0,Clay,0,Alexandr Dolgopolov,R,28.689938,David Ferrer,R,35.290897
1,Clay,1,Alexandr Dolgopolov,R,28.689938,Andrey Kuznetsov,R,26.398357
2,Clay,1,David Ferrer,R,35.290897,Fernando Verdasco,L,33.670089
3,Clay,0,Diego Sebastian Schwartzman,R,24.917180,Andrey Kuznetsov,R,26.398357
4,Clay,0,Karen Khachanov,R,21.155373,Alexandr Dolgopolov,R,28.689938

In [57]:
matchups_2016 = matchups_2016[['surface', 'player_1_win', 'player_1','player_2', 'Player_1_hand','Player_2_hand']]
# matchups_2016 = matchups_2016[['Player 1.1', 'Player 2.1', 'Player_1_Win.1']]
# matchups_2016.columns = [['player_1', 'player_2', "player_1_win"]]
matchups_2016.head()

,surface,player_1_win,player_1,player_2,Player_1_hand,Player_2_hand
0,Clay,0,Alexandr Dolgopolov,David Ferrer,R,R
1,Clay,1,Alexandr Dolgopolov,Andrey Kuznetsov,R,R
2,Clay,1,David Ferrer,Fernando Verdasco,R,L
3,Clay,0,Diego Sebastian Schwartzman,Andrey Kuznetsov,R,R
4,Clay,0,Karen Khachanov,Alexandr Dolgopolov,R,R

In [ ]:
# matchups_2016['ace_pct'] = 0
# ace_pct = total_player_stats.loc['Roger Federer']['ace_pct'] - total_player_stats.loc['Milos Raonic']['ace_pct']
# print(type(ace_pct))
# matchups_2016.loc[0,'ace_pct'] = ace_pct
# matchups_2016.head()

In [58]:
matchups_2016['ace_pct'] = 0
matchups_2016['df_pct'] = 0
matchups_2016['first_serve_pct'] = 0
matchups_2016['broken_pct'] = 0
matchups_2016['breaking_pct'] = 0
matchups_2016['break_conversion_pct'] = 0
matchups_2016["surface_win_pct"] = 0
matchups_2016["player_hand_win_pct"] = 0
count_unknown_hand = 0

for index, row in matchups_2016.iterrows():
    player_1 = row['player_1']
    player_2 = row['player_2']
    if player_1 in total_player_stats.index and player_2 in total_player_stats.index:
        ace_pct = total_player_stats.loc[player_1]['ace_pct'] - total_player_stats.loc[player_2]['ace_pct']
        df_pct = total_player_stats.loc[player_1]['df_pct'] - total_player_stats.loc[player_2]['df_pct']
        first_serve_pct = total_player_stats.loc[player_1]['first_serve_won_pct'] - total_player_stats.loc[player_2]['first_serve_won_pct']
        broken_pct = total_player_stats.loc[player_1]['broken_pct'] - total_player_stats.loc[player_2]['broken_pct']
        breaking_pct = total_player_stats.loc[player_1]['breaking_pct'] - total_player_stats.loc[player_2]['breaking_pct']
        break_conversion_pct = total_player_stats.loc[player_1]['break_conversion_pct'] - total_player_stats.loc[player_2]['break_conversion_pct']
        if row["surface"] == "Hard":
            surface_win_pct = total_player_stats.loc[player_1]["win_pct_hard"]-total_player_stats.loc[player_2]["win_pct_hard"]
        elif row["surface"] == "Clay":
            surface_win_pct = total_player_stats.loc[player_1]["win_pct_clay"]-total_player_stats.loc[player_2]["win_pct_clay"]
        elif row["surface"] == "Grass":
            surface_win_pct = total_player_stats.loc[player_1]["win_pct_grass"]-total_player_stats.loc[player_2]["win_pct_grass"]
        else:
            print("something went wrong...")
        
        if row["Player_1_hand"] == "R":
            if row["Player_2_hand"] == "R":
                player_hand_win_pct = total_player_stats.loc[player_1]["right_hand_win_pct"]-total_player_stats.loc[player_2]["right_hand_win_pct"]
            elif row["Player_2_hand"] == "L":
                player_hand_win_pct = total_player_stats.loc[player_1]["Left_hand_win_pct"]-total_player_stats.loc[player_2]["right_hand_win_pct"]
            else:
                print("unknown")
                count_unknown_hand+=1   
        elif row["Player_1_hand"] == "L":
            if row["Player_2_hand"] == "R":
                player_hand_win_pct = total_player_stats.loc[player_1]["right_hand_win_pct"]-total_player_stats.loc[player_2]["Left_hand_win_pct"]
            elif row["Player_2_hand"] == "L":
                player_hand_win_pct = total_player_stats.loc[player_1]["Left_hand_win_pct"]-total_player_stats.loc[player_2]["Left_hand_win_pct"]
            else:
                print("unknown")
                count_unknown_hand+=1
            
            
        matchups_2016.loc[index, 'ace_pct'] =  ace_pct
        matchups_2016.loc[index, 'df_pct'] = df_pct
        matchups_2016.loc[index, 'first_serve_pct'] = first_serve_pct
        matchups_2016.loc[index, 'broken_pct'] = broken_pct
        matchups_2016.loc[index, 'breaking_pct'] =  breaking_pct
        matchups_2016.loc[index, 'break_conversion_pct'] = break_conversion_pct
        matchups_2016.loc[index, 'surface_win_pct'] = surface_win_pct
        matchups_2016.loc[index, "player_hand_win_pct"] = player_hand_win_pct
    else: 
        continue
    
len(matchups_2016)

unknown
unknown
unknown
something went wrong...
something went wrong...
something went wrong...
something went wrong...
something went wrong...
something went wrong...
something went wrong...
unknown
unknown
unknown
unknown
unknown

2872

In [62]:
matchups_2016 = matchups_2016[matchups_2016.first_serve_pct != 0]
len(matchups1_2016)

2511

In [63]:
matchups_2016.head()

,surface,player_1_win,player_1,player_2,Player_1_hand,Player_2_hand,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct
0,Clay,0,Alexandr Dolgopolov,David Ferrer,R,R,0.058473,0.003827,0.036051,0.011237,-0.076718,-0.036004,-0.126263,-0.091737
1,Clay,1,Alexandr Dolgopolov,Andrey Kuznetsov,R,R,0.024493,0.000768,-0.014330,0.019776,-0.023977,-0.022118,0.010101,-0.019841
2,Clay,1,David Ferrer,Fernando Verdasco,R,L,-0.044185,-0.009779,-0.028074,0.011122,0.050696,0.035498,0.045455,-0.100000
3,Clay,0,Diego Sebastian Schwartzman,Andrey Kuznetsov,R,R,-0.041389,-0.012123,-0.083581,0.081048,0.063382,0.067013,0.017045,-0.091270
4,Clay,0,Karen Khachanov,Alexandr Dolgopolov,R,R,0.003451,-0.007213,0.011761,-0.046018,0.016777,0.049394,0.000000,0.052521

In [64]:
parameter_match_ups = pd.read_csv('matchups_parameters_2.csv')

In [65]:
parameter_match_ups.head()

,Unnamed: 0,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses,parameters_value
0,0,Roger Federer,Dominic Thiem,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Roger Federer', 'Gilles Muller', 'David Goff...","['Marin Cilic', 'Denis Kudla', 'James Duckwort...",1,4,8,4,0.020000
1,1,Roger Federer,Bernard Tomic,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Milos Raonic', 'Teymuraz Gabashvili', 'Andy ...","['Kei Nishikori', 'Radek Stepanek', 'Nicolas M...",0,2,3,2,0.000000
2,2,Roger Federer,Grigor Dimitrov,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Roger Federer', 'Viktor Troicki', 'Roger Fed...","['Viktor Troicki', 'Gilles Simon', 'Gilles Mul...",0,5,2,3,0.000000
3,3,Roger Federer,Marin Cilic,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Dominic Thiem', 'Roberto Bautista Agut', 'Al...","['Hyeon Chung', 'Thiemo De Bakker', 'Albert Ra...",1,4,4,2,0.020000
4,4,Roger Federer,Lucas Pouille,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Milos Raonic', 'Milos Raonic', 'Andrey Kuzne...","['David Goffin', 'Yoshihito Nishioka', 'David ...",1,2,4,2,0.033333

In [66]:
del parameter_match_ups["Unnamed: 0"]

In [67]:
parameter_match_ups.head(5)

,player_1,player_2,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses,parameters_value
0,Roger Federer,Dominic Thiem,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Roger Federer', 'Gilles Muller', 'David Goff...","['Marin Cilic', 'Denis Kudla', 'James Duckwort...",1,4,8,4,0.020000
1,Roger Federer,Bernard Tomic,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Milos Raonic', 'Teymuraz Gabashvili', 'Andy ...","['Kei Nishikori', 'Radek Stepanek', 'Nicolas M...",0,2,3,2,0.000000
2,Roger Federer,Grigor Dimitrov,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Roger Federer', 'Viktor Troicki', 'Roger Fed...","['Viktor Troicki', 'Gilles Simon', 'Gilles Mul...",0,5,2,3,0.000000
3,Roger Federer,Marin Cilic,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Dominic Thiem', 'Roberto Bautista Agut', 'Al...","['Hyeon Chung', 'Thiemo De Bakker', 'Albert Ra...",1,4,4,2,0.020000
4,Roger Federer,Lucas Pouille,"['Milos Raonic', 'Novak Djokovic', 'Jo Wilfrie...","['Dominic Thiem', 'Grigor Dimitrov', 'Tobias K...","['Milos Raonic', 'Milos Raonic', 'Andrey Kuzne...","['David Goffin', 'Yoshihito Nishioka', 'David ...",1,2,4,2,0.033333

In [70]:
merging_matching = pd.merge(matchups_2016, parameter_match_ups, how='left', left_on=['player_1','player_2'], right_on = ['player_1','player_2'])

In [71]:
merging_matching.head()

,surface,player_1_win,player_1,player_2,Player_1_hand,Player_2_hand,ace_pct,df_pct,first_serve_pct,broken_pct,...,player_hand_win_pct,player_1_losses,player_1_wins,player_2_losses,player_2_wins,player_1_losses_in_player_2_wins,player_2_losses_in_player_1_wins,player_1_wins_in_player_2_wins,player_1_losses_in_player_2_losses,parameters_value
0,Clay,0,Alexandr Dolgopolov,David Ferrer,R,R,0.058473,0.003827,0.036051,0.011237,...,-0.091737,"['Grigor Dimitrov', 'Roger Federer', 'Diego Se...","['Alexander Sarkissian', 'Thomaz Bellucci', 'R...","['Illya Marchenko', 'Jack Sock', 'Andy Murray'...","['Lukas Rosol', 'Matthew Barton', 'Peter Gojow...",0,3,3,2,0.00
1,Clay,1,Alexandr Dolgopolov,Andrey Kuznetsov,R,R,0.024493,0.000768,-0.014330,0.019776,...,-0.019841,"['Grigor Dimitrov', 'Roger Federer', 'Diego Se...","['Alexander Sarkissian', 'Thomaz Bellucci', 'R...","['Rafael Nadal', 'Gael Monfils', 'Viktor Troic...","['Ricardas Berankis', 'Marsel Ilhan', 'Ryan Ha...",1,1,5,1,0.05
2,Clay,1,David Ferrer,Fernando Verdasco,R,L,-0.044185,-0.009779,-0.028074,0.011122,...,-0.100000,"['Illya Marchenko', 'Jack Sock', 'Andy Murray'...","['Lukas Rosol', 'Matthew Barton', 'Peter Gojow...","['Novak Djokovic', 'Dudi Sela', 'Renzo Olivo',...","['Malek Jaziri', 'Rafael Nadal', 'Martin Kliza...",4,4,5,4,0.05
3,Clay,0,Diego Sebastian Schwartzman,Andrey Kuznetsov,R,R,-0.041389,-0.012123,-0.083581,0.081048,...,-0.091270,"['John Millman', 'Paolo Lorenzi', 'Dominic Thi...","['Alexandr Dolgopolov', 'Joao Souza', 'Horacio...","['Rafael Nadal', 'Gael Monfils', 'Viktor Troic...","['Ricardas Berankis', 'Marsel Ilhan', 'Ryan Ha...",1,1,1,2,0.05
4,Clay,0,Karen Khachanov,Alexandr Dolgopolov,R,R,0.003451,-0.007213,0.011761,-0.046018,...,0.052521,"['Gilles Muller', 'Alexandr Dolgopolov', 'Albe...","['Roberto Bautista Agut', 'Aljaz Bedene', 'Alj...","['Grigor Dimitrov', 'Roger Federer', 'Diego Se...","['Alexander Sarkissian', 'Thomaz Bellucci', 'R...",1,0,1,2,0.10

In [72]:
merging_matching = merging_matching.dropna(axis=0,how="any")

In [73]:
del merging_matching["player_1_losses"]
del merging_matching["player_1_wins"]
del merging_matching["player_2_losses"]
del merging_matching["player_2_wins"]
del merging_matching["player_1_losses_in_player_2_wins"]
del merging_matching["player_1_losses_in_player_2_losses"]
del merging_matching["player_1_wins_in_player_2_wins"]
del merging_matching["player_2_losses_in_player_1_wins"]

In [74]:
merging_matching.head()

,surface,player_1_win,player_1,player_2,Player_1_hand,Player_2_hand,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct,parameters_value
0,Clay,0,Alexandr Dolgopolov,David Ferrer,R,R,0.058473,0.003827,0.036051,0.011237,-0.076718,-0.036004,-0.126263,-0.091737,0.00
1,Clay,1,Alexandr Dolgopolov,Andrey Kuznetsov,R,R,0.024493,0.000768,-0.014330,0.019776,-0.023977,-0.022118,0.010101,-0.019841,0.05
2,Clay,1,David Ferrer,Fernando Verdasco,R,L,-0.044185,-0.009779,-0.028074,0.011122,0.050696,0.035498,0.045455,-0.100000,0.05
3,Clay,0,Diego Sebastian Schwartzman,Andrey Kuznetsov,R,R,-0.041389,-0.012123,-0.083581,0.081048,0.063382,0.067013,0.017045,-0.091270,0.05
4,Clay,0,Karen Khachanov,Alexandr Dolgopolov,R,R,0.003451,-0.007213,0.011761,-0.046018,0.016777,0.049394,0.000000,0.052521,0.10

In [75]:
len(merging_matching)

2511

In [60]:
#parameter_match_ups[parameter_match_ups.player_1==matchups_2016.player_1 and parameter_match_ups.player_2==matchups_2016.player_2]

In [61]:
#parameter_match_ups.player_1==matchups_2016.player_1

In [76]:
merging_matching.to_csv("merging_matching_first_inputs_2.csv")

In [ ]:
##if you ran the previous code, no need to run this
merging_matching = pd.read_csv("merging_matching_first_inputs.csv")
del merging_matching["Unnamed: 0"]
merging_matching.head()

In [77]:
merging_matching.head()

,surface,player_1_win,player_1,player_2,Player_1_hand,Player_2_hand,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct,parameters_value
0,Clay,0,Alexandr Dolgopolov,David Ferrer,R,R,0.058473,0.003827,0.036051,0.011237,-0.076718,-0.036004,-0.126263,-0.091737,0.00
1,Clay,1,Alexandr Dolgopolov,Andrey Kuznetsov,R,R,0.024493,0.000768,-0.014330,0.019776,-0.023977,-0.022118,0.010101,-0.019841,0.05
2,Clay,1,David Ferrer,Fernando Verdasco,R,L,-0.044185,-0.009779,-0.028074,0.011122,0.050696,0.035498,0.045455,-0.100000,0.05
3,Clay,0,Diego Sebastian Schwartzman,Andrey Kuznetsov,R,R,-0.041389,-0.012123,-0.083581,0.081048,0.063382,0.067013,0.017045,-0.091270,0.05
4,Clay,0,Karen Khachanov,Alexandr Dolgopolov,R,R,0.003451,-0.007213,0.011761,-0.046018,0.016777,0.049394,0.000000,0.052521,0.10

In [78]:
X = merging_matching.drop(["player_1_win", "player_1", "player_2", "surface", "Player_1_hand", "Player_2_hand"], axis=1)
y = merging_matching["player_1_win"]
print(X.shape, y.shape)

(2511, 9) (2511,)

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [80]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [81]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [82]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.6441848114710568
Testing Data Score: 0.6640127388535032

In [83]:
predictions_prob = classifier.predict_proba(X_test)
predictions1 = classifier.predict(X_test)

In [84]:
clean_data = [[item for item in row] for row in predictions_prob]

In [85]:
player_prob = pd.DataFrame(clean_data, columns=["player_1_prob","player_2_prob"])

In [86]:
player_prob.head()

   player_1_prob  player_2_prob
0       0.391128       0.608872
1       0.532908       0.467092
2       0.720337       0.279663
3       0.424102       0.575898
4       0.520997       0.479003

In [ ]:
#pd.DataFrame({"Prediction": predictions1, "Actual": y_test}).reset_index(drop=True).head()

In [87]:
predictions_dataframe = X_test

In [88]:
player_prob['index'] = predictions_dataframe.index
player_prob = player_prob.set_index('index')

In [89]:
player_prob.head()

       player_1_prob  player_2_prob
index
82          0.391128       0.608872
482         0.532908       0.467092
76          0.720337       0.279663
226         0.424102       0.575898
956         0.520997       0.479003

In [90]:
player_prob_merge = predictions_dataframe.join(player_prob, how = "inner")

In [91]:
player_prob_merge.head()

,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct,parameters_value,player_1_prob,player_2_prob
index,,,,,,,,,,,
82,-0.017829,0.011624,0.004529,-0.005140,0.029482,-0.165838,0.173077,-0.015152,0.050000,0.391128,0.608872
482,0.028191,-0.007283,0.024311,-0.029602,-0.085983,-0.026827,0.000000,-0.228571,0.000000,0.532908,0.467092
76,-0.052111,-0.006114,-0.096441,0.149325,0.042355,0.061040,-0.416667,-0.270435,0.083333,0.720337,0.279663
226,0.068169,-0.003853,0.105335,-0.097423,-0.022898,-0.015865,0.113725,0.094406,0.066667,0.424102,0.575898
956,-0.054779,0.015192,-0.028456,0.010116,0.003867,-0.005877,-0.095238,0.045690,0.040000,0.520997,0.479003

In [92]:
player_prob_merge["Prediction"] = predictions1

In [93]:
player_prob_merge["Actual"] = y_test

In [94]:
player_prob_merge.head(5)

,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct,parameters_value,player_1_prob,player_2_prob,Prediction,Actual
index,,,,,,,,,,,,,
82,-0.017829,0.011624,0.004529,-0.005140,0.029482,-0.165838,0.173077,-0.015152,0.050000,0.391128,0.608872,1,0
482,0.028191,-0.007283,0.024311,-0.029602,-0.085983,-0.026827,0.000000,-0.228571,0.000000,0.532908,0.467092,0,0
76,-0.052111,-0.006114,-0.096441,0.149325,0.042355,0.061040,-0.416667,-0.270435,0.083333,0.720337,0.279663,0,0
226,0.068169,-0.003853,0.105335,-0.097423,-0.022898,-0.015865,0.113725,0.094406,0.066667,0.424102,0.575898,1,1
956,-0.054779,0.015192,-0.028456,0.010116,0.003867,-0.005877,-0.095238,0.045690,0.040000,0.520997,0.479003,0,0

In [95]:
players = merging_matching[["player_1", "player_2"]]

In [96]:
players.head()

                      player_1             player_2
0          Alexandr Dolgopolov         David Ferrer
1          Alexandr Dolgopolov     Andrey Kuznetsov
2                 David Ferrer    Fernando Verdasco
3  Diego Sebastian Schwartzman     Andrey Kuznetsov
4              Karen Khachanov  Alexandr Dolgopolov

In [97]:
final_result_1 = players.join(player_prob_merge, how  ="inner")

In [98]:
final_result_1 = final_result_1.rename(index=str, columns={"player_1_prob": "player_2_prob","player_2_prob":"player_1_prob"})

In [99]:
final_result_1.to_csv("results_predicting_all_2017.csv")

In [98]:
final_result_1

,player_1,player_2,ace_pct,df_pct,first_serve_pct,broken_pct,breaking_pct,break_conversion_pct,surface_win_pct,player_hand_win_pct,parameters_value,player_2_prob,player_1_prob,Prediction,Actual
7,Andrey Kuznetsov,Pablo Carreno Busta,0.010513,0.019261,0.041994,-0.025323,-0.039409,-0.056557,-0.079545,-0.062626,0.050000,0.532612,0.467388,0,1
8,Renzo Olivo,Diego Sebastian Schwartzman,0.024739,0.025787,0.024126,-0.018480,-0.108947,-0.109881,-0.024038,-0.047619,0.100000,0.534785,0.465215,0,0
9,Ernests Gulbis,Karen Khachanov,0.016413,0.023243,-0.002516,0.059607,-0.045100,-0.071111,-0.055556,-0.288235,0.000000,0.560332,0.439668,0,0
21,Dustin Brown,Thomaz Bellucci,0.023452,-0.006448,0.031019,-0.056696,-0.006071,0.040565,0.211111,0.269841,0.000000,0.354249,0.645751,1,1
22,Mikael Ymer,Henri Laaksonen,-0.026513,-0.029299,0.024677,-0.207337,0.060870,0.000000,-0.333333,-0.400000,0.000000,0.618355,0.381645,0,0
23,Elias Ymer,Fernando Verdasco,-0.026365,-0.007604,-0.074152,0.103402,-0.112201,-0.095169,-0.303030,-0.500000,0.100000,0.727767,0.272233,0,0
26,John Isner,Bjorn Fratangelo,0.197971,-0.007597,0.168457,-0.188771,-0.087505,-0.076479,0.600000,0.142857,0.000000,0.228035,0.771965,1,1
30,Tobias Kamke,Matthew Ebden,-0.026755,-0.012199,0.126984,-0.270536,0.157509,0.084135,0.000000,0.555556,0.000000,0.315529,0.684471,1,0
34,Akira Santillan,Bjorn Fratangelo,-0.002899,-0.001933,-0.013605,0.076923,-0.194030,-0.393939,0.000000,-0.428571,0.000000,0.555423,0.444577,0,0
35,Matthew Ebden,Lukas Lacko,-0.025575,0.017661,-0.181435,0.344048,-0.057225,-0.153846,-0.400000,-0.333333,0.000000,0.726545,0.273455,0,1
36,Tobias Kamke,Adrian Mannarino,-0.049521,0.002702,-0.053074,0.063419,0.046083,0.061439,-0.615385,-0.466667,0.000000,0.773726,0.226274,0,1
38,Ivo Karlovic,Denis Kudla,0.166215,0.018344,0.118846,-0.207964,-0.109732,-0.118919,0.527273,0.327778,0.020000,0.227527,0.772473,1,1
46,Victor Estrella,Konstantin Kravchuk,-0.028862,0.003358,-0.042410,0.020833,0.061756,0.169081,0.400000,0.350000,0.000000,0.291850,0.708150,1,0
69,Ryan Harrison,John Isner,-0.158214,0.009315,-0.071406,0.111671,0.081629,0.085525,-0.104762,-0.095238,0.050000,0.563809,0.436191,0,0
70,Ryan Harrison,Kyle Edmund,0.020430,0.003256,0.028481,-0.039952,-0.014776,0.003808,-0.014652,0.007440,0.020000,0.487006,0.512994,1,1
76,Dudi Sela,Jack Sock,-0.052111,-0.006114,-0.096441,0.149325,0.042355,0.061040,-0.416667,-0.270435,0.083333,0.720337,0.279663,0,0
81,Gilles Muller,Quentin Halys,0.087049,-0.016169,0.088192,-0.095459,-0.042036,-0.052123,0.230769,0.580000,0.000000,0.291454,0.708546,1,1
82,Donald Young,Lukas Lacko,-0.017829,0.011624,0.004529,-0.005140,0.029482,-0.165838,0.173077,-0.015152,0.050000,0.391128,0.608872,1,0
87,John Millman,Francis Tiafoe,-0.014055,-0.009702,-0.020391,-0.006262,0.061803,0.076957,0.302083,0.233333,0.000000,0.323229,0.676771,1,1
91,Reilly Opelka,Malek Jaziri,0.112119,0.008424,0.061254,-0.149642,-0.107118,-0.101803,0.180556,-0.133333,0.000000,0.415998,0.584002,1,0
102,Joao Sousa,Henri Laaksonen,-0.012518,-0.031747,0.012248,-0.037915,0.022527,-0.047395,0.190476,0.050980,0.000000,0.377246,0.622754,1,1
104,Dustin Brown,Denis Istomin,0.002210,0.022989,0.027775,-0.054217,0.050737,0.065609,0.300000,0.204444,0.000000,0.321520,0.678480,1,0
107,Renzo Olivo,Robin Haase,-0.028699,0.027560,-0.040376,0.038284,-0.001758,0.002539,-0.006993,-0.023333,0.000000,0.493850,0.506150,1,0
109,Joao Sousa,Santiago Giraldo,-0.015297,0.004602,-0.000719,0.011260,0.022527,-0.026231,0.160173,0.075980,0.050000,0.409696,0.590304,1,1
115,Federico Delbonis,Leonardo Mayer,0.000547,0.000215,0.007849,0.000613,0.042841,0.060754,0.251748,0.023810,0.000000,0.376526,0.623474,1,0
121,Jan Lennard Struff,Leonardo Mayer,0.026814,0.010328,0.053446,0.011914,0.016149,-0.010370,-0.051282,0.068826,0.100000,0.511492,0.488508,0,0
122,Horacio Zeballos,Jiri Vesely,-0.018015,0.001591,-0.001607,0.035550,-0.078821,0.022276,-0.433333,-0.300000,0.100000,0.740725,0.259275,0,0
125,Benoit Paire,Nicolas Kicker,0.078110,0.017668,0.106523,0.007733,-0.042450,-0.080000,0.140351,0.086667,0.000000,0.410725,0.589275,1,0
127,Cedrik Marcel Stebe,Diego Sebastian Schwartzman,-0.013353,0.018421,-0.160498,0.217884,-0.092804,-0.216403,-0.562500,-0.666667,0.000000,0.795613,0.204387,0,0
129,Leonardo Mayer,Albert Ramos,0.015133,0.011772,0.027568,-0.019246,-0.063613,-0.054513,-0.209135,0.018519,0.100000,0.591747,0.408253,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,Nicolas Kicker,Steve Johnson,-0.094497,0.003562,-0.134785,0.132740,0.120430,0.134321,-0.733333,-0.166667,0.000000,0.773370,0.226630,0,0
2418,Facundo Bagnis,Radu Albot,0.022004,0.025094,0.035490,-0.044478,-0.036518,-0.071429,-0.500000,0.384615,0.000000,0.601309,0.398691,0,0
2419,Viktor Troicki,Florian Mayer,0.038215,0.006603,0.011200,-0.001286,0.030303,0.010048,-0.500000,0.038503,0.033333,0.663876,0.336124,0,0
2426,Evgeny Donskoy,Alexander Zverev,-0.019279,-0.028359,-0.036187,0.044056,-0.094661,-0.068898,-0.416667,-0.388563,0.060000,0.730888,0.269112,0,0
2430,John Isner,Taylor Harry Fritz,0.151501,-0.003610,0.088647,-0.148518,-0.073910,-0.032751,0.400000,0.147186,0.014286,0.299801,0.700199,1,1
2436,Jared Donaldson,Janko Tipsarevic,0.002368,0.005362,-0.016143,0.045077,0.039574,0.065650,-0.333333,0.024038,0.100000,0.637925,0.362075,0,1
2440,Borna Coric,Ryan Harrison,-0.014722,-0.010561,-0.047396,0.032189,0.009806,-0.055315,0.000000,-0.009524,0.033333,0.483307,0.516693,1,0
2443,Alexander Ward,Kyle Edmund,-0.026777,0.003106,-0.041519,0.102166,-0.168446,-0.199177,-0.400000,-0.397436,0.000000,0.722058,0.277942,0,0
2447,Ernests Gulbis,Victor Estrella,0.074491,0.029993,0.088824,-0.024496,-0.025259,-0.094776,-0.400000,-0.050000,0.050000,0.640752,0.359248,0,1
2454,Jo Wilfried Tsonga,Simone Bolelli,0.049183,0.022063,0.109436,-0.125375,0.104457,0.031691,0.800000,0.452196,0.000000,0.137068,0.862932,1,1
2457,Ruben Bemelmans,Daniil Medvedev,-0.012352,-0.005974,-0.028125,-0.078558,-0.154674,0.123810,-0.500000,0.333333,0.000000,0.668364,0.331636,0,1
2460,Damir Dzumhur,Aljaz Bedene,-0.075538,-0.007708,-0.106453,0.067288,0.086501,0.082072,0.100000,0.070690,0.042857,0.441171,0.558829,1,0
2461,Gilles Muller,Lukas Rosol,0.113210,0.009738,0.099584,-0.081037,0.005588,-0.023287,0.722222,0.380000,0.033333,0.178894,0.821106,1,1
2468,Alexander Zverev,Francis Tiafoe,0.009182,0.023070,0.029605,-0.046596,0.070928,0.049603,0.750000,0.494624,0.000000,0.157404,0.842596,1,1
2469,Marcos Baghdatis,Grigor Dimitrov,0.013033,0.004466,0.020629,0.021109,0.011402,0.047416,0.145455,-0.063636,0.061538,0.458416,0.541584,1,0
2472,Dusan Lajovic,Roger Federer,-0.052561,0.004515,-0.089471,0.083774,-0.085487,-0.035244,-0.769231,-0.306527,0.100000,0.829881,0.170119,0,0
2473,Gilles Simon,Dominic Thiem,-0.040240,-0.008076,-0.066476,0.082164,0.035006,0.040936,-0.377778,-0.191961,0.064286,0.680819,0.319181,0,0
2475,David Ferrer,Steve Darcis,-0.005480,0.000119,-0.028404,-0.036662,0.052534,0.039782,0.400000,0.198880,0.000000,0.287096,0.712904,1,1
2477,Kyle Edmund,Gael Monfils,-0.034479,-0.001940,-0.024819,0.061959,-0.080569,-0.058682,0.400000,-0.262019,0.050000,0.406978,0.593022,1,0
2479,Ernests Gulbis,Juan Martin Del Potro,0.023493,0.027522,-0.020467,0.081822,-0.064682,-0.032602,-0.625000,-0.402703,0.100000,0.800735,0.199265,0,1
2485,Rafael Nadal,Karen Khachanov,-0.069662,-0.014989,-0.056075,0.016423,0.139444,0.027308,0.000000,0.117391,0.025000,0.433511,0.566489,1,1
2487,Roberto Bautista Agut,Kei Nishikori,-0.001369,-0.003639,-0.028012,0.031179,-0.015632,-0.019011,-0.200000,-0.102767,0.053846,0.595701,0.404299,0,1
2489,Milos Raonic,Albert Ramos,0.115580,0.008601,0.117248,-0.136650,-0.061762,-0.055699,0.333333,0.268519,0.018182,0.302525,0.697475,1,1
2492,Jared Donaldson,Dominic Thiem,-0.009804,0.007750,-0.006178,0.076228,-0.016356,0.050979,-0.777778,-0.277592,0.033333,0.813779,0.186221,0,0
2494,Adrian Mannarino,Gael Monfils,-0.046768,0.002605,-0.042470,0.087689,-0.043867,-0.050548,0.615385,-0.158333,0.100000,0.321157,0.678843,1,1
2495,Novak Djokovic,Ernests Gulbis,-0.063912,-0.027928,-0.005795,-0.098601,0.161414,0.079630,0.666667,0.583333,0.000000,0.151135,0.848865,1,1
2497,Kevin Anderson,Sam Querrey,0.004444,0.017655,-0.027951,0.000526,-0.025977,-0.045368,-0.266667,-0.093842,0.037500,0.607828,0.392172,0,0
2504,Sam Querrey,Andy Murray,0.077840,0.005437,0.036211,0.001355,-0.181843,-0.084111,-0.333333,-0.376623,0.085714,0.720177,0.279823,0,1
2506,Roger Federer,Milos Raonic,-0.051175,-0.019505,-0.001429,0.006373,0.058434,0.039871,-0.064103,-0.023077,0.100000,0.528070,0.471930,0,1
2509,Roger Federer,Tomas Berdych,0.004311,-0.014867,0.015416,-0.050372,0.022763,0.003224,0.054945,0.076923,0.020000,0.435391,0.564609,1,1